export type MoveNote = {
  san: string;
  why: string;
  goal?: string;
  mistake?: string;
  tip?: string;
};

export type Opening = {
  id: string;
  name: string;
  eco: string;
  /** Side the user is being trained as. */
  trainAs: "white" | "black";
  description: string;
  /** Strategic plans in the middlegame. */
  plans: string[];
  /** Recurring tactical / structural motifs. */
  motifs: string[];
  /** Common beginner mistakes for this opening. */
  commonMistakes: string[];
  /** Annotated mainline. Index 0 = first move. */
  moves: MoveNote[];
};

export const OPENINGS: Opening[] = [
  // ───────────────── WHITE ─────────────────
  {
    id: "italian",
    name: "Italian Game",
    eco: "C50",
    trainAs: "white",
    description:
      "The oldest opening in chess. White builds a classical center and targets the vulnerable f7 square with the bishop on c4.",
    plans: [
      "Pressure f7 with the bishop on c4 and a future Ng5 or Nxe5 sacrifice",
      "Play c3 and d4 to build a strong pawn center",
      "Castle short, then look for kingside attacks with h3 / Re1",
    ],
    motifs: ["Greek-gift sacrifice on h7", "Fried Liver attack with Ng5", "Pin on Nf6 with Bg5"],
    commonMistakes: [
      "Allowing your opponent to play …Bxf2+ tricks because you castled too late",
      "Trading on c6 without a reason and helping Black's center",
      "Pushing pawns instead of finishing development",
    ],
    moves: [
      { san: "e4",  why: "Claims the center and frees the bishop and queen.", goal: "Central control", mistake: "Pushing flank pawns like a3 first." },
      { san: "e5",  why: "Black mirrors and stops e4–e5 ideas.", tip: "Symmetry is fine in the opening as long as you keep developing." },
      { san: "Nf3", why: "Develops a piece, attacks e5, prepares castling.", goal: "Develop with a threat" },
      { san: "Nc6", why: "Defends e5 and develops naturally.", mistake: "Defending with …d6 cramps the bishop." },
      { san: "Bc4", why: "Targets the weakest square in Black's camp, f7.", goal: "Pressure f7" },
      { san: "Bc5", why: "Mirrors the bishop and pressures f2.", tip: "Both sides eye the f-pawn — castling matters." },
      { san: "c3",  why: "Prepares d2–d4 to build a big center.", goal: "Pawn break d4" },
      { san: "Nf6", why: "Develops and attacks the e4 pawn.", mistake: "Skipping …Nf6 lets White play d4 unchallenged." },
      { san: "d4",  why: "The thematic central break.", goal: "Open lines for the bishops" },
      { san: "exd4", why: "Black takes to break White's center.", tip: "Don't let White keep a full center for free." },
      { san: "cxd4", why: "Recaptures and gains a mobile pawn center.", goal: "Central majority" },
      { san: "Bb4+", why: "Checks and forces White to deal with the bishop.", tip: "Checks before castling save a tempo." },
    ],
  },
  {
    id: "ruy-lopez",
    name: "Ruy Lopez",
    eco: "C60",
    trainAs: "white",
    description:
      "The Spanish opening — White pins the knight defending e5 and prepares a long, slow positional squeeze.",
    plans: [
      "Build the classical center with c3 and d4",
      "Maneuver the knight via Nb1–d2–f1–g3 (Spanish knight tour)",
      "Generate pressure on the half-open f-file after exchanges",
    ],
    motifs: ["Pin on c6", "d2–d4 break", "Kingside knight reroute"],
    commonMistakes: [
      "Trading on c6 too early and easing Black's development",
      "Forgetting that …b5 + …Na5 attacks the bishop",
      "Neglecting kingside safety before launching pawn pushes",
    ],
    moves: [
      { san: "e4",  why: "Claims the center.", goal: "Central control" },
      { san: "e5",  why: "Solid classical reply." },
      { san: "Nf3", why: "Hits e5 and develops.", goal: "Develop with tempo" },
      { san: "Nc6", why: "Defends e5." },
      { san: "Bb5", why: "Pins the knight defending e5 — the signature Spanish move.", goal: "Indirect pressure on e5" },
      { san: "a6",  why: "Asks the bishop a question (Morphy Defense).", tip: "Forcing the bishop to declare its intentions." },
      { san: "Ba4", why: "Keeps the pin while staying flexible.", mistake: "Bxc6 too early helps Black's center." },
      { san: "Nf6", why: "Attacks e4 and develops." },
      { san: "O-O", why: "King safety first.", goal: "Castle before opening lines" },
      { san: "Be7", why: "Prepares to castle." },
      { san: "Re1", why: "Defends e4 and prepares c3 + d4.", goal: "Support the d4 break" },
      { san: "b5",  why: "Gains queenside space and chases the bishop." },
    ],
  },
  {
    id: "london",
    name: "London System",
    eco: "D02",
    trainAs: "white",
    description:
      "A reliable, easy-to-learn system. White develops the bishop to f4 outside the pawn chain and plays for a long-term kingside attack.",
    plans: [
      "Solid pawn triangle on d4–e3–c3",
      "Trade dark-squared bishops or land the bishop on a strong outpost",
      "Slow kingside expansion with h3, Ne5, f4",
    ],
    motifs: ["Bxh7+ Greek gift", "Knight outpost on e5", "Queen lift via Qd2–Qf2"],
    commonMistakes: [
      "Allowing …Qb6 hitting b2 without preparation",
      "Locking the bishop in with e2–e3 before Bf4",
      "Drifting without a plan — the London needs purpose",
    ],
    moves: [
      { san: "d4",  why: "Stakes a claim in the center.", goal: "Central pawn" },
      { san: "d5",  why: "Symmetric central reply." },
      { san: "Nf3", why: "Develops and supports d4.", tip: "Always develop the knight before the bishop here." },
      { san: "Nf6", why: "Mirrors development." },
      { san: "Bf4", why: "The defining London move — bishop out before e3 locks it in.", goal: "Active bishop" },
      { san: "c5",  why: "The principled break against d4." },
      { san: "e3",  why: "Solidifies the pawn chain.", mistake: "Playing e3 before Bf4 traps the bishop." },
      { san: "Nc6", why: "Develops and adds pressure on d4." },
      { san: "c3",  why: "Builds the London triangle d4-e3-c3." },
      { san: "e6",  why: "Opens the bishop and prepares development." },
      { san: "Nbd2", why: "Flexible development supporting e4 break later.", goal: "Prepare Ne5" },
      { san: "Bd6", why: "Challenges the f4 bishop." },
    ],
  },
  {
    id: "queens-gambit",
    name: "Queen's Gambit",
    eco: "D06",
    trainAs: "white",
    description:
      "White offers the c-pawn to deflect Black's d-pawn and dominate the center. Black almost never accepts.",
    plans: [
      "If Black accepts, regain the pawn with e3 + Bxc4 and play for central majority",
      "If Black declines, build slow positional pressure with Nc3 + Bg5",
      "Minority attack on the queenside with b2–b4–b5",
    ],
    motifs: ["Minority attack", "IQP positions", "Carlsbad pawn structure"],
    commonMistakes: [
      "Trying to hold the c4 pawn after capture with b3 (loses material)",
      "Playing Nf3 before c4 and missing tactical motifs",
      "Neglecting the c-file pressure",
    ],
    moves: [
      { san: "d4",  why: "Classical center pawn." },
      { san: "d5",  why: "Direct central contest." },
      { san: "c4",  why: "The gambit — undermines d5.", goal: "Deflect Black's center" },
      { san: "e6",  why: "Declines, builds a solid pawn chain (QGD)." },
      { san: "Nc3", why: "Adds pressure on d5." },
      { san: "Nf6", why: "Develops and defends d5." },
      { san: "Bg5", why: "Pins the f6 knight, deepening the pressure on d5.", goal: "Pile up on d5" },
      { san: "Be7", why: "Breaks the pin and prepares castling." },
      { san: "e3",  why: "Solid, opens the bishop, supports d4." },
      { san: "O-O", why: "Black gets the king to safety." },
      { san: "Nf3", why: "Completes minor-piece development.", tip: "All four minor pieces out before plans." },
      { san: "Nbd7", why: "Standard QGD setup — supports c5 break." },
    ],
  },
  {
    id: "english",
    name: "English Opening",
    eco: "A10",
    trainAs: "white",
    description:
      "A flank opening with c4 — flexible, transposes to many setups, and gives White a Sicilian with an extra tempo.",
    plans: [
      "Fianchetto the kingside bishop and pressure the long diagonal",
      "Reversed Sicilian structures with d3 + e4",
      "Queenside expansion with b4–b5",
    ],
    motifs: ["Long-diagonal pressure", "Reversed Sicilian", "c-file pressure"],
    commonMistakes: [
      "Going passive after the fianchetto without a plan",
      "Allowing …e5–e4 to gain too much space",
      "Letting Black control d4 without a fight",
    ],
    moves: [
      { san: "c4",  why: "Flank pawn — fights for d5 from the side.", goal: "Flexible center" },
      { san: "e5",  why: "Reversed Sicilian by Black." },
      { san: "Nc3", why: "Develops and contests d5." },
      { san: "Nf6", why: "Develops and contests e4." },
      { san: "g3",  why: "Prepares the long-diagonal fianchetto.", goal: "Bishop on g2" },
      { san: "d5",  why: "Central counter-thrust." },
      { san: "cxd5", why: "Opens the c-file and removes Black's center pawn." },
      { san: "Nxd5", why: "Recaptures with the knight." },
      { san: "Bg2", why: "Fianchetto eyeing d5 and Black's queenside.", goal: "Long-diagonal pressure" },
      { san: "Nb6", why: "Reroutes the knight after Bg2 hits d5." },
      { san: "Nf3", why: "Develops, prepares castling." },
      { san: "Nc6", why: "Standard development." },
    ],
  },
  {
    id: "vienna",
    name: "Vienna Game",
    eco: "C25",
    trainAs: "white",
    description:
      "A sneaky 1.e4 system — White develops the knight to c3 first, keeping the option of f4 and a King's-Gambit-style attack.",
    plans: [
      "Play f2–f4 to open the f-file (Vienna Gambit)",
      "Build a classical center with d3 and slow buildup",
      "Trade pieces favorably after f4–f5",
    ],
    motifs: ["f4 break", "Open f-file", "Knight hops to d5"],
    commonMistakes: [
      "Pushing f4 too early without development",
      "Trading the c3 knight without compensation",
      "Forgetting that …Bb4 pins the knight",
    ],
    moves: [
      { san: "e4",  why: "Classical center." },
      { san: "e5",  why: "Classical response." },
      { san: "Nc3", why: "Vienna move-order — develops without committing the f-knight.", goal: "Keep f4 available" },
      { san: "Nf6", why: "Attacks e4." },
      { san: "f4",  why: "The Vienna Gambit — open the f-file for attack.", tip: "Aggressive but principled — supported by Nc3." },
      { san: "d5",  why: "The best reply, striking back in the center." },
      { san: "fxe5", why: "Captures and opens lines." },
      { san: "Nxe4", why: "Recaptures the central pawn." },
      { san: "Nf3", why: "Develops with tempo on the e5 pawn." },
      { san: "Be7", why: "Develops, prepares castling." },
      { san: "d3",  why: "Asks the knight to retreat." },
      { san: "Nxc3", why: "Trades to relieve pressure." },
    ],
  },
  {
    id: "scotch",
    name: "Scotch Game",
    eco: "C45",
    trainAs: "white",
    description:
      "White challenges the center immediately with d4 — opens lines fast and avoids deep Ruy Lopez theory.",
    plans: [
      "Open the position quickly and out-develop Black",
      "Place the knight on a strong central outpost",
      "Trade into a favorable endgame with better pawn structure",
    ],
    motifs: ["Knight on d5", "Open e-file", "Quick Qf3 ideas"],
    commonMistakes: [
      "Allowing …Bb4+ tactics that disrupt development",
      "Trading queens too early and losing initiative",
      "Underestimating …Bc5 putting pressure on f2",
    ],
    moves: [
      { san: "e4",  why: "Central control." },
      { san: "e5",  why: "Classical reply." },
      { san: "Nf3", why: "Hits e5." },
      { san: "Nc6", why: "Defends e5." },
      { san: "d4",  why: "The Scotch — immediate center break.", goal: "Open the position" },
      { san: "exd4", why: "Forced capture; otherwise Black loses the center." },
      { san: "Nxd4", why: "Recaptures with the knight.", tip: "Knight on d4 is excellent — central and active." },
      { san: "Bc5", why: "Develops with pressure on the knight." },
      { san: "Be3", why: "Reinforces d4 and prepares to trade dark-squared bishops." },
      { san: "Qf6", why: "Adds pressure on d4 and prepares …Nge7." },
      { san: "c3",  why: "Solidifies and prepares Nc2 or queen moves." },
      { san: "Nge7", why: "Develops the knight to a flexible square." },
    ],
  },
  {
    id: "kings-gambit",
    name: "King's Gambit",
    eco: "C30",
    trainAs: "white",
    description:
      "The romantic gambit — White sacrifices the f-pawn to rip open the f-file and attack the king.",
    plans: [
      "Rapid development and open the f-file",
      "Build a big center with d4 and e5",
      "Direct attack on f7 and Black's king",
    ],
    motifs: ["Open f-file", "Sacrificial attacks", "Bishop on c4 + f-file"],
    commonMistakes: [
      "Trying to hold the pawn instead of attacking",
      "Allowing …Qh4+ ideas",
      "Forgetting king safety while attacking",
    ],
    moves: [
      { san: "e4",  why: "Classical center." },
      { san: "e5",  why: "Direct symmetric play." },
      { san: "f4",  why: "Gambits the f-pawn for fast development and open lines.", goal: "Open the f-file" },
      { san: "exf4", why: "Accepted — Black takes and challenges White to attack." },
      { san: "Nf3", why: "Develops and stops …Qh4+.", tip: "Always play Nf3 before any other development here." },
      { san: "g5",  why: "Black tries to hold the pawn (Classical Defense)." },
      { san: "Bc4", why: "Develops with attack on f7.", goal: "Pressure f7" },
      { san: "Bg7", why: "Fianchettoes to control the long diagonal." },
      { san: "d4",  why: "Builds the dream center." },
      { san: "d6",  why: "Solid defensive structure." },
      { san: "Nc3", why: "Completes development." },
      { san: "Nc6", why: "Develops the queenside knight." },
    ],
  },
  {
    id: "catalan",
    name: "Catalan Opening",
    eco: "E00",
    trainAs: "white",
    description:
      "A modern positional weapon — White combines d4 + c4 with a kingside fianchetto for long-term pressure on the long diagonal.",
    plans: [
      "Long-diagonal pressure with Bg2",
      "Slow squeeze on the queenside",
      "Trade pieces favorably and convert structural advantages",
    ],
    motifs: ["Long-diagonal pin", "Catalan bind", "Qa4+ pickup ideas"],
    commonMistakes: [
      "Allowing …dxc4 + …b5 without compensation",
      "Trading the g2 bishop without a clear reason",
      "Going for tactics before the bishop's diagonal works",
    ],
    moves: [
      { san: "d4",  why: "Central pawn." },
      { san: "Nf6", why: "Indian setup — flexible development." },
      { san: "c4",  why: "Queen's pawn opening with c4." },
      { san: "e6",  why: "Solid, prepares …d5." },
      { san: "g3",  why: "Defining Catalan move — fianchetto.", goal: "Long-diagonal control" },
      { san: "d5",  why: "Stakes a claim in the center." },
      { san: "Bg2", why: "The Catalan bishop — eyes b7 forever." },
      { san: "Be7", why: "Quiet development, prepares castling." },
      { san: "Nf3", why: "Develops, supports d4." },
      { san: "O-O", why: "Standard king safety." },
      { san: "O-O", why: "White castles too — both sides settle." },
      { san: "dxc4", why: "Open Catalan — Black takes the pawn but White gets activity." },
    ],
  },
  {
    id: "jobava-london",
    name: "Jobava London",
    eco: "D00",
    trainAs: "white",
    description:
      "A sharp modern hybrid — Bf4 with Nc3 and an early Nb5 hop to provoke weaknesses near Black's king.",
    plans: [
      "Provoke …a6 weakness with Nb5 ideas",
      "Quick kingside attack with h4–h5",
      "Trade the dark-squared bishop favorably",
    ],
    motifs: ["Nb5 hop", "h4–h5 push", "Bxc7 sacrifices in some lines"],
    commonMistakes: [
      "Pushing pawns without development",
      "Allowing …c5 + …Qb6 without preparation",
      "Trading the strong f4 bishop too cheaply",
    ],
    moves: [
      { san: "d4",  why: "Central pawn." },
      { san: "d5",  why: "Symmetric reply." },
      { san: "Nc3", why: "Aggressive — knight before c-pawn (vs the classical London).", goal: "Threaten e4" },
      { san: "Nf6", why: "Develops and stops e4." },
      { san: "Bf4", why: "Hits c7, threatens Nb5.", goal: "Provoke weakness" },
      { san: "a6",  why: "Stops Nb5 (but creates a weakness)." },
      { san: "e3",  why: "Solidifies and opens the bishop." },
      { san: "c5",  why: "The standard central break." },
      { san: "dxc5", why: "Takes to keep tension." },
      { san: "e6",  why: "Plans to recapture with …Bxc5." },
      { san: "Nf3", why: "Develops." },
      { san: "Bxc5", why: "Recaptures." },
    ],
  },

  // ───────────────── BLACK ─────────────────
  {
    id: "sicilian",
    name: "Sicilian Defense",
    eco: "B20",
    trainAs: "black",
    description:
      "Black's most popular reply to 1.e4 — asymmetric structure with massive winning chances. Sharp and tactical.",
    plans: [
      "Counter-attack on the queenside (open c-file)",
      "Maneuver knights to active squares (Najdorf-style)",
      "Punish White's overextension in the center",
    ],
    motifs: ["c-file pressure", "…d5 break", "Knight on c4 outpost"],
    commonMistakes: [
      "Forgetting development while grabbing pawns",
      "Castling kingside into a White attack without preparation",
      "Playing …e5 too early and weakening d5",
    ],
    moves: [
      { san: "e4",  why: "White's most aggressive first move." },
      { san: "c5",  why: "The Sicilian — fights for d4 asymmetrically.", goal: "Asymmetric counterplay" },
      { san: "Nf3", why: "Standard development." },
      { san: "d6",  why: "Prepares …Nf6 without losing the e-pawn (Najdorf-style)." },
      { san: "d4",  why: "Open Sicilian — White accepts the challenge." },
      { san: "cxd4", why: "Black trades the c-pawn for activity.", goal: "Open c-file" },
      { san: "Nxd4", why: "Recaptures with the knight." },
      { san: "Nf6", why: "Develops and attacks e4." },
      { san: "Nc3", why: "Defends e4." },
      { san: "a6",  why: "Najdorf — prevents Nb5 and prepares …b5 for queenside expansion.", tip: "The Najdorf is one of the most fought lines in chess." },
      { san: "Be2", why: "Quiet development." },
      { san: "e5",  why: "Gains space and challenges the knight." },
    ],
  },
  {
    id: "french",
    name: "French Defense",
    eco: "C00",
    trainAs: "black",
    description:
      "Solid pawn chain. Black accepts a slightly cramped position to strike back later with …c5 and …f6.",
    plans: [
      "Strike at the d4 pawn with …c5",
      "Counterattack the e5 pawn with …f6",
      "Activate the bad bishop on c8 via …b6 + …Ba6",
    ],
    motifs: ["…c5 break", "…f6 break", "Knight outpost on e4"],
    commonMistakes: [
      "Leaving the light-squared bishop trapped behind pawns",
      "Castling kingside into a strong White attack in the Advance Variation",
      "Trading the wrong knight on e4",
    ],
    moves: [
      { san: "e4",  why: "White's most popular first move." },
      { san: "e6",  why: "French — prepares …d5 with support.", goal: "Solid central counter" },
      { san: "d4",  why: "White claims the full center." },
      { san: "d5",  why: "Challenges e4 directly." },
      { san: "Nc3", why: "Defends e4 — the main line." },
      { san: "Nf6", why: "Pressures e4 further." },
      { san: "Bg5", why: "Pins the knight to add pressure." },
      { san: "Be7", why: "Breaks the pin." },
      { san: "e5",  why: "Advances and gains space." },
      { san: "Nfd7", why: "Retreats with a plan — eyes …c5 and …f6 breaks.", tip: "The knight on d7 supports the breaks that define the French." },
      { san: "Bxe7", why: "White trades dark-squared bishops." },
      { san: "Qxe7", why: "Recaptures naturally." },
    ],
  },
  {
    id: "caro-kann",
    name: "Caro-Kann Defense",
    eco: "B10",
    trainAs: "black",
    description:
      "A rock-solid defense for Black. Slower than the Sicilian but with a healthy pawn structure and an active light-squared bishop.",
    plans: [
      "Get the light-squared bishop out before …e6",
      "Solid pawn structure as a base for the endgame",
      "Counter in the center with …c5 at the right moment",
    ],
    motifs: ["Bishop on f5 / g4 outside the chain", "…c5 break", "Endgame technique"],
    commonMistakes: [
      "Trapping the bishop behind …e6 too early",
      "Allowing h4–h5 without a plan in the Classical",
      "Missing the …c5 break and ending up passive",
    ],
    moves: [
      { san: "e4",  why: "White's classical first move." },
      { san: "c6",  why: "Caro-Kann — prepares …d5 with support.", goal: "Solid base, free the bishop" },
      { san: "d4",  why: "Standard central pawn." },
      { san: "d5",  why: "Direct central contest." },
      { san: "Nc3", why: "Defends e4." },
      { san: "dxe4", why: "Releases the tension." },
      { san: "Nxe4", why: "Recaptures." },
      { san: "Bf5", why: "Classical Caro-Kann — bishop out before …e6.", goal: "Activate the bishop" },
      { san: "Ng3", why: "Hits the bishop." },
      { san: "Bg6", why: "Maintains the bishop on a good diagonal." },
      { san: "h4",  why: "Aggressive — White asks the bishop a question." },
      { san: "h6",  why: "Creates a safe square (h7) for the bishop." },
    ],
  },
  {
    id: "scandinavian",
    name: "Scandinavian Defense",
    eco: "B01",
    trainAs: "black",
    description:
      "An immediate central challenge. Black takes the e-pawn with the d-pawn and accepts an early queen move for clear plans.",
    plans: [
      "Develop quickly with …Nf6, …c6, …Bf5 / …Bg4",
      "Castle queenside in some lines for opposite-side attacks",
      "Use the queen as a piece, not a target",
    ],
    motifs: ["Bishop pair", "…O-O-O setup", "Pressure on the d-file"],
    commonMistakes: [
      "Letting the queen get chased around losing tempi",
      "Skipping …c6 and walking into Nc3 tempo gains",
      "Trading the bishops too cheaply",
    ],
    moves: [
      { san: "e4",  why: "Classical first move." },
      { san: "d5",  why: "Scandinavian — directly challenges e4.", goal: "Trade central pawn for development" },
      { san: "exd5", why: "Forced — otherwise Black gets a great center." },
      { san: "Qxd5", why: "Recaptures with the queen.", tip: "Queen moves to a3/d6/d8 — pick one and play with a plan." },
      { san: "Nc3", why: "Develops with tempo on the queen." },
      { san: "Qa5", why: "Pins the knight and stays active." },
      { san: "d4",  why: "Builds the center." },
      { san: "Nf6", why: "Develops naturally." },
      { san: "Nf3", why: "Standard development." },
      { san: "c6",  why: "Creates a retreat for the queen on c7 and supports …d5." },
      { san: "Bc4", why: "Targets f7." },
      { san: "Bf5", why: "Develops the light-squared bishop actively." },
    ],
  },
  {
    id: "pirc",
    name: "Pirc Defense",
    eco: "B07",
    trainAs: "black",
    description:
      "A hypermodern defense — Black lets White build a big center, then attacks it with pieces and timely pawn breaks.",
    plans: [
      "Strike the center with …e5 or …c5",
      "Fianchetto and use the bishop on g7 as the main piece",
      "Counterattack rather than match White pawn for pawn",
    ],
    motifs: ["Long-diagonal bishop", "…e5 break", "…c5 break"],
    commonMistakes: [
      "Letting White's center become permanent",
      "Trading the strong g7 bishop without reason",
      "Castling into a White Austrian Attack",
    ],
    moves: [
      { san: "e4",  why: "Classical center." },
      { san: "d6",  why: "Pirc — flexible, allows kingside fianchetto." },
      { san: "d4",  why: "White builds a big center." },
      { san: "Nf6", why: "Develops and attacks e4." },
      { san: "Nc3", why: "Defends e4." },
      { san: "g6",  why: "Prepares the fianchetto.", goal: "Long-diagonal bishop" },
      { san: "Nf3", why: "Develops." },
      { san: "Bg7", why: "The defining Pirc bishop." },
      { san: "Be2", why: "Modest development." },
      { san: "O-O", why: "King safety." },
      { san: "O-O", why: "White castles too." },
      { san: "c6",  why: "Prepares …b5 and supports …d5 / …e5 ideas." },
    ],
  },
  {
    id: "kings-indian",
    name: "King's Indian Defense",
    eco: "E60",
    trainAs: "black",
    description:
      "A hypermodern weapon — Black allows a big White center, then explodes with kingside pawn storms in the middlegame.",
    plans: [
      "Push …f5, …g5, …h5 for a kingside attack",
      "Wait for White's c5 then counter with …b6 or queenside play",
      "Exchange dark-squared bishops favorably",
    ],
    motifs: ["…f5 break", "Kingside pawn storm", "Knight maneuvers …Nh5–f4"],
    commonMistakes: [
      "Trading dark-squared bishops voluntarily",
      "Pushing kingside pawns before completing development",
      "Letting White close the center comfortably",
    ],
    moves: [
      { san: "d4",  why: "Classical first move for White." },
      { san: "Nf6", why: "Indian Defense move-order." },
      { san: "c4",  why: "Queen's pawn opening." },
      { san: "g6",  why: "Prepares the King's Indian fianchetto." },
      { san: "Nc3", why: "Develops and supports e4." },
      { san: "Bg7", why: "Long-diagonal bishop — Black's strongest piece." },
      { san: "e4",  why: "White goes for the full center.", tip: "Don't get scared — the KID thrives against big centers." },
      { san: "d6",  why: "Supports …e5 and stops e4–e5." },
      { san: "Nf3", why: "Standard development." },
      { san: "O-O", why: "King safety before pawn storms." },
      { san: "Be2", why: "Classical White development." },
      { san: "e5",  why: "The thematic KID break — locks the center for the kingside attack.", goal: "Lock center for kingside storm" },
    ],
  },
  {
    id: "nimzo-indian",
    name: "Nimzo-Indian Defense",
    eco: "E20",
    trainAs: "black",
    description:
      "One of Black's most respected defenses — pins the c3 knight with …Bb4 and aims for doubled c-pawns and central control.",
    plans: [
      "Give up the bishop pair to double White's c-pawns",
      "Blockade on the dark squares",
      "Central play with …d5 or …c5",
    ],
    motifs: ["…Bxc3 doubling pawns", "Central blockade", "Knight on e4 outpost"],
    commonMistakes: [
      "Trading the bishop too early without compensation",
      "Letting White untangle the doubled pawns",
      "Allowing a comfortable e4 push by White",
    ],
    moves: [
      { san: "d4",  why: "Classical opening move." },
      { san: "Nf6", why: "Flexible Indian setup." },
      { san: "c4",  why: "Queen's pawn opening." },
      { san: "e6",  why: "Prepares …Bb4." },
      { san: "Nc3", why: "Develops and supports e4." },
      { san: "Bb4", why: "Nimzo-Indian — pins the knight, fights for e4.", goal: "Stop e4, double White's pawns" },
      { san: "e3",  why: "Rubinstein — solid response." },
      { san: "O-O", why: "Castles first." },
      { san: "Bd3", why: "Develops the bishop." },
      { san: "d5",  why: "Strikes the center." },
      { san: "Nf3", why: "Develops." },
      { san: "c5",  why: "Challenges the center." },
    ],
  },
  {
    id: "slav",
    name: "Slav Defense",
    eco: "D10",
    trainAs: "black",
    description:
      "A solid answer to the Queen's Gambit — Black supports d5 with the c-pawn instead of locking in the c8-bishop.",
    plans: [
      "Develop the c8 bishop before …e6",
      "Capture on c4 and follow with …b5 in some lines",
      "Solid endgame with a healthy pawn structure",
    ],
    motifs: ["Bishop on f5 / g4", "…dxc4 + …b5", "Symmetric structures"],
    commonMistakes: [
      "Locking the bishop in with …e6 first",
      "Pushing …b5 without enough support",
      "Trading bishops carelessly",
    ],
    moves: [
      { san: "d4",  why: "Standard." },
      { san: "d5",  why: "Direct central contest." },
      { san: "c4",  why: "Queen's Gambit." },
      { san: "c6",  why: "Slav — supports d5 without blocking the bishop." },
      { san: "Nf3", why: "Develops." },
      { san: "Nf6", why: "Develops." },
      { san: "Nc3", why: "Develops." },
      { san: "dxc4", why: "Black takes the pawn — plans …b5 to hold it." },
      { san: "a4",  why: "Stops …b5." },
      { san: "Bf5", why: "Develops the bishop actively outside the pawn chain.", goal: "Free the light-squared bishop" },
      { san: "e3",  why: "Solid and recaptures c4 later." },
      { san: "e6",  why: "Completes the pawn chain." },
    ],
  },
  {
    id: "dutch",
    name: "Dutch Defense",
    eco: "A80",
    trainAs: "black",
    description:
      "A combative reply to 1.d4 — Black grabs kingside space with …f5 and plays for a kingside attack.",
    plans: [
      "Stonewall, Classical, or Leningrad — pick a structure",
      "Kingside attack with …Qe8–h5 in Leningrad",
      "Use the e4 outpost in Stonewall",
    ],
    motifs: ["Stonewall pawn chain", "…f5–f4 push", "Knight outpost on e4"],
    commonMistakes: [
      "Weakening e6 too much without compensation",
      "Forgetting kingside king safety after …f5",
      "Misplacing the c8 bishop",
    ],
    moves: [
      { san: "d4",  why: "Standard." },
      { san: "f5",  why: "Dutch — bold kingside space grab.", goal: "Kingside aggression" },
      { san: "g3",  why: "White fianchettoes to fight for the long diagonal." },
      { san: "Nf6", why: "Develops." },
      { san: "Bg2", why: "Long-diagonal bishop." },
      { san: "g6",  why: "Leningrad Dutch — Black fianchettoes too." },
      { san: "Nf3", why: "Develops." },
      { san: "Bg7", why: "Mirror fianchetto." },
      { san: "O-O", why: "King safety." },
      { san: "O-O", why: "King safety." },
      { san: "c4",  why: "Stakes a claim on the queenside." },
      { san: "d6",  why: "Solid Leningrad setup, prepares …e5." },
    ],
  },
  {
    id: "modern",
    name: "Modern Defense",
    eco: "B06",
    trainAs: "black",
    description:
      "Hypermodern, flexible — Black fianchettoes immediately and decides on a pawn structure later based on what White does.",
    plans: [
      "Choose between …d6 + …e5 or …c5 setups",
      "Long-diagonal bishop as the main piece",
      "Counter-strike against White's center",
    ],
    motifs: ["Fianchetto bishop", "…c5 / …e5 breaks", "Knight to f6 or e7"],
    commonMistakes: [
      "Falling behind in development",
      "Letting White play e5 and gain too much space",
      "Trading the Bg7 too easily",
    ],
    moves: [
      { san: "e4",  why: "Classical." },
      { san: "g6",  why: "Modern — immediate fianchetto." },
      { san: "d4",  why: "White builds the center." },
      { san: "Bg7", why: "The defining piece of the Modern." },
      { san: "Nc3", why: "Develops." },
      { san: "d6",  why: "Supports …e5 and …Nf6." },
      { san: "Nf3", why: "Develops." },
      { san: "a6",  why: "Prepares …b5 for queenside play." },
      { san: "a4",  why: "Stops …b5." },
      { san: "Nf6", why: "Develops the knight." },
      { san: "Be2", why: "Modest development." },
      { san: "O-O", why: "King safety." },
    ],
  },
];

export function findOpening(id: string): Opening | undefined {
  return OPENINGS.find((o) => o.id === id);
}
